name: Build & clang-tidy
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true  # Fetch submodules: true
    - name: CMake
      env:
        CC: clang
        CXX: clang++
      run: cmake -B ./build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    - uses: arkedge/action-clang-tidy@v1.5.0
      with:
        workdir: ./build